---
url: "https://s3.eu-central-1.amazonaws.com/documentation.reportix.com/documentation/reportix-server/api/index.json"
dom_id: "#swagger-ui"
validatorUrl: "https://online.swagger.io/validator"
oauth2RedirectUrl: "http://localhost:3200/oauth2-redirect.html"
